import Head from "next/head";

import { Outfit } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Game from "@/components/Game/Game";

const inter = Outfit({ subsets: ["latin"], weight: ["700"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Game />
    </>
  );
}
